# Generated by Django 4.2.11 on 2024-06-21 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("ktag.ch", "ktag.ch"),
                            ("aargau.cloud", "aargau.cloud"),
                        ],
                        max_length=200,
                    ),
                ),
                ("primary_ip", models.GenericIPAddressField()),
                (
                    "cpu",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(16)]
                    ),
                ),
                (
                    "memory",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(65536)]
                    ),
                ),
                (
                    "disk",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(65536)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pending"),
                            ("ACT", "Active"),
                            ("APP", "Approved"),
                            ("REJ", "Rejected"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("SLEM", "SLE Micro"),
                            ("SLES", "SLE Server"),
                            ("LEAP", "openSUSE Leap"),
                        ],
                        default="SLEM",
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
