# Generated by Django 4.2.11 on 2024-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="network",
            field=models.CharField(
                choices=[
                    ("VLAN-105", "VLAN-105: 192.168.11.0/24"),
                    ("VLAN-106", "VLAN-106: 192.168.122.0/24"),
                ],
                default="VLAN-105",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(default="SPPA-178", max_length=200),
        ),
        migrations.AlterField(
            model_name="server",
            name="primary_ip",
            field=models.GenericIPAddressField(default="192.168.11.101"),
        ),
    ]
