# Generated by Django 5.0.6 on 2024-06-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_alter_server_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("major_version", models.IntegerField()),
                ("minor_version", models.IntegerField()),
                ("patch_level", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="server",
            name="os",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="servers.operatingsystem",
            ),
        ),
    ]
