# Generated by Django 4.2.11 on 2024-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0006_domain_alter_server_status_alter_server_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Der Hostname wird automatisch generiert, wenn keiner vergeben wird.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="primary_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Es wird die nächste freie IP aus dem zugewisesenen Netz automatisch zugewiesen.",
                null=True,
                protocol="IPv4",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="groups",
            field=models.ManyToManyField(related_name="servers", to="servers.group"),
        ),
    ]
