# Generated by Django 4.2.16 on 2025-04-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0007_group_alter_server_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("mac", models.CharField(blank=True, max_length=17)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lan", "LAN"),
                            ("wifi", "WiFi"),
                            ("dmz", "DMZ"),
                            ("mgm", "Management"),
                            ("svc", "Service"),
                        ],
                        default="lan",
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="servers.server",
                    ),
                ),
            ],
        ),
    ]
